import React from "react";
import {cleanup,fireEvent,render,screen,within} from "@testing-library/react";
import {afterEach,describe,expect,it} from "vitest";
import App from "./App";
import {deriveState,STEPS} from "./data/mockData";

afterEach(cleanup);

describe("deterministic replay",()=>{
  it("returns fresh canonical state for every direct step",()=>{for(let step=0;step<STEPS.length;step+=1){const expected=deriveState(step),changed=deriveState(step);changed.buses[0].load=999;changed.stops[0].queue=999;expect(deriveState(step)).toEqual(expected);}});
  it("matches the full-bus overflow scenario",()=>{const initial=deriveState(0);expect(initial.buses.find(bus=>bus.id==="E1")).toMatchObject({load:8,eta:2,status:"COMMUTING"});expect(initial.buses.find(bus=>bus.id==="E2")).toMatchObject({load:0,eta:17,status:"IDLE",position:"KDOJ"});expect(initial.stops.find(stop=>stop.id==="kdse_e").queue).toBe(18);expect(initial.stops.find(stop=>stop.id==="kdoj_e").queue).toBe(22);expect(deriveState(1).buses.find(bus=>bus.id==="E1").load).toBe(28);expect(deriveState(1).stops.find(stop=>stop.id==="kdoj_e").queue).toBe(2);expect(deriveState(7).buses.find(bus=>bus.id==="E2")).toMatchObject({eta:7,etaGain:5,status:"COMMUTING"});expect(deriveState(9).buses.find(bus=>bus.id==="E2").load).toBe(20);});
});

it("navigates all ten steps forward and backward five times without drift",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),previous=screen.getByRole("button",{name:"Previous step"});for(let run=0;run<5;run+=1){for(let step=1;step<10;step+=1)fireEvent.click(next);expect(screen.getByText("7:52 · E2 collects all 18 at KDSE")).toBeInTheDocument();expect(screen.getByText("KDSE queue cleared")).toBeInTheDocument();expect(within(screen.getByLabelText("Stop KDSE")).getByText("0")).toBeInTheDocument();for(let step=9;step>0;step-=1)fireEvent.click(previous);expect(screen.getByText("7:40 · E1 approaches two busy stops")).toBeInTheDocument();expect(screen.getByText(/Press the right arrow/)).toBeInTheDocument();}});

it("clears a simulated plan change when replay navigation resumes",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});for(let step=1;step<=5;step+=1)fireEvent.click(next);fireEvent.click(screen.getByRole("button",{name:"Change the plan for Bus E2"}));fireEvent.click(screen.getByRole("button",{name:"Return to schedule"}));expect(screen.getByText("Bus returned to schedule")).toBeInTheDocument();fireEvent.click(next);expect(screen.queryByText("Bus returned to schedule")).not.toBeInTheDocument();expect(screen.getByText("Bus E2 is assigned to the overflow")).toBeInTheDocument();});

it("shows the missed-bus cause and the safe early departure",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),priority=screen.getByRole("region",{name:"Most important update"});expect(within(priority).getByText("18 students waiting")).toBeInTheDocument();expect(screen.getByLabelText("Demo time")).toHaveTextContent("07:40:00");fireEvent.click(next);expect(screen.getByText("Bus full at KDOJ")).toBeInTheDocument();fireEvent.click(next);expect(screen.getByText("Missed bus reports received")).toBeInTheDocument();for(let step=3;step<=5;step+=1)fireEvent.click(next);expect(screen.getByText("15-MINUTE GAP ✓")).toBeInTheDocument();fireEvent.click(next);expect(within(priority).getByText("Bus E2 assigned")).toBeInTheDocument();fireEvent.click(next);expect(screen.getByText("5 min earlier")).toBeInTheDocument();expect(screen.getByLabelText("Demo time")).toHaveTextContent("07:45:00");fireEvent.click(next);fireEvent.click(next);expect(within(priority).getByText("All 18 students are on board · Nobody left waiting")).toBeInTheDocument();expect(screen.getByLabelText("Demo time")).toHaveTextContent("07:52:00");});

it("uses aggregate missed-bus reports rather than one log per student",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});fireEvent.click(next);fireEvent.click(next);expect(screen.getAllByText("Missed bus reports received")).toHaveLength(1);expect(screen.getByText("Students at KDSE reported that E1 passed full · 18 are still waiting")).toBeInTheDocument();});
