import React from "react";
import {cleanup,fireEvent,render,screen,within} from "@testing-library/react";
import {afterEach,describe,expect,it} from "vitest";
import App from "./App";
import {deriveState,STEPS} from "./data/mockData";

afterEach(cleanup);

describe("deterministic replay",()=>{
  it("returns fresh canonical state for every direct step",()=>{for(let step=0;step<STEPS.length;step+=1){const expected=deriveState(step),changed=deriveState(step);changed.buses[0].load=999;changed.stops[0].queue=999;expect(deriveState(step)).toEqual(expected);}});
  it("matches the student PWA early-departure scenario",()=>{const initial=deriveState(0);expect(initial.buses.find(bus=>bus.id==="E2")).toMatchObject({load:0,eta:14,status:"IDLE",position:"KDOJ"});expect(initial.stops.find(stop=>stop.id==="kdse_e").queue).toBe(11);expect(initial.stops.find(stop=>stop.id==="kdoj_e").queue).toBe(5);expect(deriveState(2).stops.find(stop=>stop.id==="kdse_e").queue).toBe(16);expect(deriveState(7).buses.find(bus=>bus.id==="E2")).toMatchObject({eta:7,load:5,status:"COMMUTING"});expect(deriveState(9).stops.find(stop=>stop.id==="kdse_e")).toMatchObject({queue:0,level:"LOW"});expect(deriveState(9).buses.find(bus=>bus.id==="E2").load).toBe(21);});
});

it("navigates all ten steps forward and backward five times without visible drift",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),previous=screen.getByRole("button",{name:"Previous step"});for(let run=0;run<5;run+=1){for(let step=1;step<10;step+=1)fireEvent.click(next);expect(screen.getByText("Bus E2 picks up all 16 students")).toBeInTheDocument();expect(screen.getByText("Students picked up")).toBeInTheDocument();expect(within(screen.getByLabelText("Stop KDSE")).getByText("0")).toBeInTheDocument();for(let step=9;step>0;step-=1)fireEvent.click(previous);expect(screen.getByText("Buses are running normally")).toBeInTheDocument();expect(screen.getByText(/Press the right arrow/)).toBeInTheDocument();}});

it("clears a simulated override when demo navigation resumes",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});for(let step=1;step<=5;step+=1)fireEvent.click(next);fireEvent.click(screen.getByRole("button",{name:"Change the plan for Bus E2"}));expect(screen.getByRole("dialog",{name:"Change Bus E2 plan"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Return to schedule"}));expect(screen.getByText("Bus returned to schedule")).toBeInTheDocument();fireEvent.click(next);expect(screen.queryByText("Bus returned to schedule")).not.toBeInTheDocument();expect(screen.getByText("Bus E2 is assigned to KDSE")).toBeInTheDocument();});

it("keeps priority guidance and demo time aligned with replay state",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),priority=screen.getByRole("region",{name:"Most important update"});expect(within(priority).getByText("KDSE")).toBeInTheDocument();expect(within(priority).getByText("11 students waiting")).toBeInTheDocument();expect(screen.getByLabelText("Demo time")).toHaveTextContent("09:41:07");fireEvent.click(next);fireEvent.click(next);expect(within(priority).getByText("Busy stop")).toBeInTheDocument();expect(within(priority).getByText("16 students waiting")).toBeInTheDocument();for(let step=3;step<=6;step+=1)fireEvent.click(next);expect(within(priority).getByText("Bus E2 assigned")).toBeInTheDocument();fireEvent.click(next);fireEvent.click(next);expect(screen.getAllByText("Extra response avoided").length).toBeGreaterThan(1);fireEvent.click(next);expect(within(priority).getByText("Bus E2 is here")).toBeInTheDocument();expect(within(priority).getByText("All 16 students are on board · Nobody left waiting")).toBeInTheDocument();expect(screen.getByLabelText("Demo time")).toHaveTextContent("09:41:34");});

it("logs queue-level changes instead of every student signal",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});fireEvent.click(next);expect(screen.getByLabelText("Stop KDSE")).toHaveAttribute("aria-current","step");expect(screen.queryByText("Student added")).not.toBeInTheDocument();expect(screen.getByText(/Press the right arrow/)).toBeInTheDocument();fireEvent.click(next);expect(screen.getByLabelText("KDSE stop More students waiting")).toHaveAttribute("aria-current","step");fireEvent.click(next);fireEvent.click(next);expect(screen.getByLabelText("Bus E2")).toHaveAttribute("aria-current","step");expect(screen.getByText("Heading to busy stop · KDSE")).toBeInTheDocument();expect(screen.getByLabelText("Bus E2 Checking earlier departure")).toHaveAttribute("aria-current","step");fireEvent.click(next);fireEvent.click(next);fireEvent.click(next);expect(screen.getByText("7 min earlier")).toBeInTheDocument();});
