import React from "react";
import {cleanup,fireEvent,render,screen,within} from "@testing-library/react";
import {afterEach,describe,expect,it} from "vitest";
import App from "./App";
import {deriveState,STEPS} from "./data/mockData";

afterEach(cleanup);

describe("deterministic replay",()=>{
  it("returns fresh canonical state for every direct step",()=>{for(let step=0;step<STEPS.length;step+=1){const expected=deriveState(step),changed=deriveState(step);changed.buses[0].load=999;changed.stops[0].queue=999;expect(deriveState(step)).toEqual(expected);}});
  it("matches the student PWA early-departure scenario",()=>{expect(deriveState(0).buses.find(bus=>bus.id==="E2")).toMatchObject({load:0,eta:14,status:"IDLE",position:"Corridor E terminus"});expect(deriveState(0).stops[0].queue).toBe(11);expect(deriveState(2).stops[0].queue).toBe(16);expect(deriveState(7).buses.find(bus=>bus.id==="E2")).toMatchObject({eta:7,status:"COMMUTING"});expect(deriveState(9).stops[0]).toMatchObject({queue:0,level:"LOW"});expect(deriveState(9).buses.find(bus=>bus.id==="E2").load).toBe(25);});
});

it("navigates all ten steps forward and backward five times without visible drift",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),previous=screen.getByRole("button",{name:"Previous step"});for(let run=0;run<5;run+=1){for(let step=1;step<10;step+=1)fireEvent.click(next);expect(screen.getByText("E2 boards all 16 students at KDOJ")).toBeInTheDocument();expect(screen.getByText("BOARDING COMPLETED")).toBeInTheDocument();expect(within(screen.getByLabelText("Stop KDOJ")).getByText("0")).toBeInTheDocument();for(let step=9;step>0;step-=1)fireEvent.click(previous);expect(screen.getByText("Initial live state")).toBeInTheDocument();expect(screen.getByText(/Press →/)).toBeInTheDocument();}});

it("clears a simulated override when demo navigation resumes",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});for(let step=1;step<=5;step+=1)fireEvent.click(next);fireEvent.click(screen.getByRole("button",{name:"Override timing for Bus E2"}));expect(screen.getByRole("dialog",{name:"Override Bus E2"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Confirm override"}));expect(screen.getByText("TIMING OVERRIDE CONFIRMED")).toBeInTheDocument();fireEvent.click(next);expect(screen.queryByText("TIMING OVERRIDE CONFIRMED")).not.toBeInTheDocument();expect(screen.getByText("KDOJ claimed by Bus E2")).toBeInTheDocument();});

it("keeps priority guidance and scenario time aligned with replay state",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"}),priority=screen.getByRole("region",{name:"Current operational priority"});expect(within(priority).getByText("11 students waiting")).toBeInTheDocument();expect(screen.getByLabelText("Scenario time")).toHaveTextContent("09:41:07");fireEvent.click(next);fireEvent.click(next);expect(within(priority).getByText("High demand")).toBeInTheDocument();expect(within(priority).getByText("16 students waiting")).toBeInTheDocument();for(let step=3;step<=6;step+=1)fireEvent.click(next);expect(within(priority).getByText("Response assigned to E2")).toBeInTheDocument();fireEvent.click(next);fireEvent.click(next);expect(screen.getByText("DUPLICATE RESPONSE SUPPRESSED")).toBeInTheDocument();fireEvent.click(next);expect(within(priority).getByText("E2 arrived")).toBeInTheDocument();expect(within(priority).getByText("All 16 students boarded · Queue cleared")).toBeInTheDocument();expect(screen.getByLabelText("Scenario time")).toHaveTextContent("09:41:34");});

it("links the current stop, bus, and decision across panels",()=>{render(<App/>);const next=screen.getByRole("button",{name:"Next step"});fireEvent.click(next);expect(screen.getByLabelText("Stop KDOJ")).toHaveAttribute("aria-current","step");expect(screen.getByLabelText("STOP_KDOJ_E DEMAND SIGNAL ACCEPTED")).toHaveAttribute("aria-current","step");for(let step=2;step<=4;step+=1)fireEvent.click(next);expect(screen.getByLabelText("Bus E2")).toHaveAttribute("aria-current","step");expect(screen.getByText("Priority stop · KDOJ")).toBeInTheDocument();expect(screen.getByLabelText("BUS_E2 EARLY DEPARTURE EVALUATION")).toHaveAttribute("aria-current","step");fireEvent.click(next);fireEvent.click(next);fireEvent.click(next);expect(screen.getByText("↑ 7 min vs schedule")).toBeInTheDocument();});
